### ISSUE TITLE
sigpatch-updater freezes in "download complete!" msg

### ISSUE THREAD

**Issue by evertonstz** [ITotalJustice/sigpatch-updater#2]
I'm trying to update sigpatches for Hekate, after I press "A" I just get a download complete msg, but the patches never extract and the app just hangs there, only way is to force exit by pressing home button.

**Comment by ITotalJustice** [comment]
Thanks for reporting the issue.

Turns out the ams sig patch download is broken as well (the folder structure was changed).

I’ll fix this tomorrow at some point.

**Comment by ITotalJustice** [comment]
Fixed in the latest version.

Sadly I seem to have broken app updating in the previous version (it is now fixed). The new version will be uploaded to the homebrew app store later today, or you can download the latest release.
