### ISSUE TITLE
How to access this?

### ISSUE THREAD

**Issue by anriho** [ITotalJustice/sigpatch-updater#4]
I've put the .nro in my root, I'm unable to locate how to run it. I'm a bit new to this whole process so I apologize if you've heard this question a lot.

**Comment by impeeza** [comment]
Nop, you need to put the NRO file on SD:/switch/ folder, then run the program from HBL,  familiarize yourself with the basics reading a guide like https://rentry.co/SwitchHackingIsEasy

**Comment by impeeza** [comment]
please use this space as issue report, for support go to Discord or GBATemp https://gbatemp.net/threads/switch-noob-paradise-ask-questions-here.488277/

**Comment by ITotalJustice** [comment]
> please use this space as issue report, for support go to Discord or GBATemp https://gbatemp.net/threads/switch-noob-paradise-ask-questions-here.488277/

Thanks for helping out :)

I am okay with people using the issue report for asking questions btw, mainly because the issue tracker isn't busy. Good suggestion with linking the guide btw
