### ISSUE TITLE
Sigpatch host is down?

### ISSUE THREAD

**Issue by eduhenke** [ITotalJustice/sigpatch-updater#5]
I tried to install via the app and it just freezes, also trying to access https://sigmapatches.coomer.party/ returns a 504 gateway timeout error.

**Comment by eduhenke** [comment]
After waiting about 5 minutes the application successfully downloaded it

**Comment by ITotalJustice** [comment]
Yeah I should probably get around to downloading async so it doesn't look like the app has frozen 😅 when I get the chance I'll push a new release, I'll keep this open until then.

**Comment by impeeza** [comment]
Something fishy is going on on the hosting side:

![image](https://github.com/ITotalJustice/sigpatch-updater/assets/41979604/7ee4cd62-6a74-41f4-83b3-4b98682ebdf1)

**Comment by arch-box** [comment]
> I tried to install via the app and it just freezes, also trying to access https://sigmapatches.coomer.party/ returns a 504 gateway timeout error.

The new domain is https://sigmapatches.su

**Comment by thiagoteles** [comment]
> > I tried to install via the app and it just freezes, also trying to access https://sigmapatches.coomer.party/ returns a 504 gateway timeout error.
> 
> The new domain is https://sigmapatches.su

how do I change the domain on the application?

**Comment by ITotalJustice** [comment]
fixed in latest release https://github.com/ITotalJustice/sigpatch-updater/commit/d43b4dfec526911bd435888029dd6d28dda33ed4
